# Generated by Django 2.2.8 on 2020-11-05 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201004_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointcloud',
            old_name='x',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='pointcloud',
            old_name='y',
            new_name='depth',
        ),
        migrations.RemoveField(
            model_name='pointcloud',
            name='z',
        ),
    ]
