# Generated by Django 3.0.5 on 2020-10-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200612_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointcloud',
            name='x',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='pointcloud',
            name='y',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='pointcloud',
            name='z',
            field=models.CharField(max_length=20000),
        ),
    ]
