# Generated by Django 2.2.8 on 2020-10-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201004_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointcloud',
            name='x',
            field=models.CharField(max_length=200000),
        ),
        migrations.AlterField(
            model_name='pointcloud',
            name='y',
            field=models.CharField(max_length=200000),
        ),
        migrations.AlterField(
            model_name='pointcloud',
            name='z',
            field=models.CharField(max_length=200000),
        ),
    ]
