# Generated by Django 2.2.13 on 2020-06-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointCloud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.CharField(max_length=20000)),
                ('y', models.CharField(max_length=20000)),
                ('z', models.CharField(max_length=20000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
