# Generated by Django 2.2.13 on 2020-06-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointcloud',
            name='x',
            field=models.CharField(max_length=200000),
        ),
        migrations.AlterField(
            model_name='pointcloud',
            name='y',
            field=models.CharField(max_length=200000),
        ),
        migrations.AlterField(
            model_name='pointcloud',
            name='z',
            field=models.CharField(max_length=200000),
        ),
    ]
